---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  String

Metadata:
  template metadata

Parameters:
  POCNameParameter:
    Type: String
    Default: Your Name

  EnvironmentParameter:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Rules:
  set of rules

Mappings:
  set of mappings

Conditions:
  set of conditions

Resources:
  set of resources

Outputs:
  set of outputs
