AWSTemplateFormatVersion: '2010-09-09'
Transform:                AWS::Serverless-2016-10-31
Description:              Deploys an AWS Lambda function that echos the string passed via an API call.

# Parameters
Parameters:
  EnvironmentParameter:
    Type:                 String
    Default:              dev
    AllowedValues:
      - dev
      - test
      - prod

  POCNameParameter:
    Type:                 String
    Default:              Your Name


# # Global Values -- These are applied to all resources
Globals:
  Function:
    Tags:
      POCName:            !Ref POCNameParameter
      Environment:        !Ref EnvironmentParameter



# Metadata:
#   template metadata
#
# Mappings:
#   set of mappings
#
# Conditions:
#   set of conditions

# Resources
Resources:
  EchoFunction:
    Type:                 AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [!Ref EnvironmentParameter, EchoFunction]]
      Handler:              echo.lambda_handler
      Runtime:              python3.8
      CodeUri:              echo.zip
      Tracing:              Active
      Timeout:              15
      Policies:
        - AWSLambdaExecute
      Events:
        ApiEvent:
          Type:             Api
          Properties:
            Path:           /echo
            Method:         get
      Environment:
        Variables:
          sqs_queue:        message_queue
          sns_topic:        message_topic


Outputs:
  EchoApi:
    Description:          "API Gateway endpoint URL for Prod stage for Hello World function"
    Value:                !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/echo/"
  EchoFunction:
    Description:          "Hello World Lambda Function ARN"
    Value:                !GetAtt EchoFunction.Arn
  EchoFunctionIamRole:
    Description:          "Implicit IAM Role created for Hello World function"
    Value:                !GetAtt EchoFunctionRole.Arn
